src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

    /**
     * @ORM\OneToMany(targetEntity=Article::class, mappedBy="user", orphanRemoval=true)
     */
    private $articles;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="user", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=Like::class, mappedBy="user")
     */
    private $likes;

    /**
     * @ORM\OneToMany(targetEntity=Share::class, mappedBy="user")
     */
    private $shares;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->shares = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setUser($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getUser() === $this) {
                $article->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Like[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setUser($this);
        }

        return $this;
    }

    public function removeLike(Like $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getUser() === $this) {
                $like->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Share[]
     */
    public function getShares(): Collection
    {
        return $this->shares;
    }

    public function addShare(Share $share): self
    {
        if (!$this->shares->contains($share)) {
            $this->shares[] = $share;
            $share->setUser($this);
        }

        return $this;
    }

    public function removeShare(Share $share): self
    {
        if ($this->shares->removeElement($share)) {
            // set the owning side to null (unless already changed)
            if ($share->getUser() === $this) {
                $share->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Gregwar\CaptchaBundle\Type\CaptchaType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('last_name', TextType::class, [
                'required' => true,
                'label' => 'Nom',
            ])
            ->add('first_name', TextType::class, [
                'required' => true,
                'label' => 'Prénom',
            ])
            ->add('email', EmailType::class, [
                'required' => true,
                'label' => 'Email',
            ])
            ->add('phone', TelType::class, [
                'required' => true,
                'label' => 'Téléphone',
            ])
            ->add('captcha', CaptchaType::class, [
                'label' => 'Captcha*',
                'attr' => ['class' => 'ml-2']
            ])
            ->add('save', SubmitType::class, [
                'label' => 'Enregistrer',
                'attr' => ['class' => 'btn-success']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Comment;
use App\Entity\Like;
use App\Entity\Share;
use App\Entity\User;
use App\Form\ChangePwdType;
use App\Form\UserType;
use App\Repository\ArticleRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * Require ROLE_USER for *every* controller method in this class.
 * @Route("/user")
 * @IsGranted("ROLE_USER")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/dashboard", name="user_dashboard")
     */
    public function userDashboard(): Response
    {
        // Get 5 latest article like/share/comment of user (by user ID)
        $fifth_article_like = $this->getDoctrine()->getRepository(Like::class)->findBy([
            'user' => $this->getUser()
        ], [
            'createAt' => 'DESC',
        ],5);

        $fifth_article_share = $this->getDoctrine()->getRepository(Share::class)->findBy([
            'user' => $this->getUser()
        ], [
            'createAt' => 'DESC',
        ],5);

        $fifth_article_comment = $this->getDoctrine()->getRepository(Comment::class)->findBy([
            'user' => $this->getUser()
        ], [
            'createAt' => 'DESC',
        ],5);

        return $this->render('user/dashboard.html.twig', [
            'fifth_article_like' => $fifth_article_like,
            'fifth_article_share' => $fifth_article_share,
            'fifth_article_comment' => $fifth_article_comment,
        ]);
    }

    /**
     * @Route("/info", name="user_info")
     */
    public function userInfo(Request $request): Response
    {
        $user = $this->getUser();

        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        // UserForm to change personnal values
        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'Information édité avec succès');
            return $this->redirectToRoute('user_info');
        }

        // Alert user
        return $this->render('user/info.html.twig', [
            'userForm' => $form->createView(),
        ]);
    }

    /**
     * @Route("/password", name="user_password")
     */
    public function userPassword(Request $request, UserPasswordEncoderInterface $passwordEncoder, UserRepository $userRepo): Response
    {
        $form = $this->createForm(ChangePwdType::class);
        $form->handleRequest($request);

        // PasswordForm to change password
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
            
            $formInfo = $form->getData();
            $old_pwd = $formInfo['oldPassword']; 
            $new_pwd = $formInfo['newPassword'];
            // Check if password is valid
            $checkPass = $passwordEncoder->isPasswordValid($user, $old_pwd);
            // If its true change password (hashed)
            if($checkPass) {
                $userRepo->upgradePassword($user, $passwordEncoder->encodePassword($user, $new_pwd));
            } else {
                $this->addFlash('error', 'Mot de passe actuelle est erroné !');
                return $this->redirectToRoute('user_password');
            }
            // Alert user
            $this->addFlash('success', 'Mot de passe changé avec succès');
            return $this->redirectToRoute('user_password');
        }

        return $this->render('user/password.html.twig', [
            'passForm' => $form->createView(),
        ]);
    }

    /**
     * @Route("/like", name="user_like")
     */
    public function userLike(Request $request, PaginatorInterface $paginator): Response
    {
        // Get all articles liked of user (by user ID)
        $articles_like = $this->getDoctrine()->getRepository(Like::class)->findBy([
            'user' => $this->getUser()
        ]);

        $articles = $paginator->paginate(
            $articles_like, // Requête contenant les données à paginer
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            10 // Nombre de résultats par page
        );

        return $this->render('user/like.html.twig', [
            'articles' => $articles
        ]);
    }

    /**
     * @Route("/share", name="user_share")
     */
    public function userShare(Request $request, PaginatorInterface $paginator): Response
    {
        // Get all articles shared of user (by user ID)
        $articles_share = $this->getDoctrine()->getRepository(Share::class)->findBy([
            'user' => $this->getUser()
        ],['createAt' => 'DESC']);

        $articles = $paginator->paginate(
            $articles_share, // Requête contenant les données à paginer
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            10 // Nombre de résultats par page
        );

        return $this->render('user/share.html.twig', [
            'articles' => $articles
        ]);
    }

    /**
     * @Route("/comment", name="user_comment")
     */
    public function userComment(Request $request, PaginatorInterface $paginator, EntityManagerInterface $em): Response
    {
        // Get all comment of user (by user ID) DESC
        $dql = "SELECT c FROM App:Comment c WHERE c.user = :user ORDER BY c.createAt DESC";
        $articles = $em->createQuery($dql);
        $articles->setParameter('user', $this->getUser()->getId());
        $articles_comment = $articles->getResult();

        $articles = $paginator->paginate(
            $articles_comment, // Requête contenant les données à paginer
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            10 // Nombre de résultats par page
        );

        return $this->render('user/comment.html.twig', [
            'articles' => $articles
        ]);
    }
}

templates/user/_latest-comment.html.twig
<section class="my-4">
    <div class="my-3">
        <h2>Vos 5 derniers articles commentés :</h2>
    </div>
    <div class="d-flex flex-column flex-lg-row">
    {% for comment in fifth_article_comment %}
        <a href="{{ path('article_show', {'id': comment.article.id}) }}" class="text-decoration-none text-reset">
            <div class="flex-grow-1 card border-secondary mb-2 mr-2">
                <div class="card-header">{{ comment.article.title }}</div>
                <div class="card-body">
                    <div>
                        {# {% if comment.image %}
                            <img src="{{ asset('/uploads/' ~ article.image.name) }}" alt="" height="200"/>
                        {% else %} #}
                            <svg xmlns="http://www.w3.org/2000/svg" class="d-block user-select-none" width="100%" height="200" aria-label="Placeholder: Image cap" focusable="false" role="img" preserveAspectRatio="xMidYMid slice" viewBox="0 0 318 180" style="font-size:1.125rem;text-anchor:middle">
                                <rect width="100%" height="100%" fill="#868e96"></rect>
                                <text x="50%" y="50%" fill="#dee2e6" dy=".3em">Pas d'image</text>
                            </svg>
                        {# {% endif %} #}
                    </div>
                    <h6 class="mt-1">
                        Catégorie : 
                        <span class="mb-1 text-secondary">{{ comment.article.category}}</span>
                    </h6>
                </div>
            </div>
        </a>
    {% endfor %}
    </div>
    {% if not fifth_article_comment %}
        <div class="text-center my-4 border p-4 text-muted">
            Vous semblez ne pas avoir commenté d'article
        </div>
    {% endif %}
</section>

templates/user/_latest-like.html.twig
<section class="my-4">
    <div class="my-3">
        <h2>Vos 5 derniers articles aimés :</h2>
    </div>
    <div class="d-flex flex-column flex-lg-row">
    {% for like in fifth_article_like %}
        <a href="{{ path('article_show', {'id': like.article.id}) }}" class="text-decoration-none text-reset">
            <div class="flex-grow-1 card border-secondary mb-2 mr-2">
                <div class="card-header">{{ like.article.title }}</div>
                <div class="card-body">
                    <div>
                        {# {% if like.image %}
                            <img src="{{ asset('/uploads/' ~ like.image.name) }}" alt="" height="200"/>
                        {% else %} #}
                            <svg xmlns="http://www.w3.org/2000/svg" class="d-block user-select-none" width="100%" height="200" aria-label="Placeholder: Image cap" focusable="false" role="img" preserveAspectRatio="xMidYMid slice" viewBox="0 0 318 180" style="font-size:1.125rem;text-anchor:middle">
                                <rect width="100%" height="100%" fill="#868e96"></rect>
                                <text x="50%" y="50%" fill="#dee2e6" dy=".3em">Pas d'image</text>
                            </svg>
                        {# {% endif %} #}
                    </div>
                    <h6 class="mt-1">
                        Catégorie : 
                        <span class="mb-1 text-secondary">{{ like.article.category}}</span>
                    </h6>
                </div>
            </div>
        </a>
    {% endfor %}
    </div>
    {% if not fifth_article_like %}
        <div class="text-center my-4 border p-4 text-muted">
            Vous semblez ne pas avoir d'article aimé
        </div>
    {% endif %}
</section>

templates/user/_latest-share.html.twig
<section class="my-4">
    <div class="my-3">
        <h2>Vos 5 derniers articles partagés :</h2>
    </div>
    <div class="d-flex flex-column flex-lg-row">
    {% for share in fifth_article_share %}
        <a href="{{ path('article_show', {'id': share.article.id}) }}" class="text-decoration-none text-reset">
            <div class="flex-grow-1 card border-secondary mb-2 mr-2">
                <div class="card-header">{{ share.article.title }}</div>
                <div class="card-body">
                    <div>
                        {# {% if share.image %}
                            <img src="{{ asset('/uploads/' ~ article.image.name) }}" alt="" height="200"/>
                        {% else %} #}
                            <svg xmlns="http://www.w3.org/2000/svg" class="d-block user-select-none" width="100%" height="200" aria-label="Placeholder: Image cap" focusable="false" role="img" preserveAspectRatio="xMidYMid slice" viewBox="0 0 318 180" style="font-size:1.125rem;text-anchor:middle">
                                <rect width="100%" height="100%" fill="#868e96"></rect>
                                <text x="50%" y="50%" fill="#dee2e6" dy=".3em">Pas d'image</text>
                            </svg>
                        {# {% endif %} #}
                    </div>
                    <h6 class="mt-1">
                        Catégorie : 
                        <span class="mb-1 text-secondary">{{ share.article.category}}</span>
                    </h6>
                </div>
            </div>
        </a>
    {% endfor %}
    </div>
    {% if not fifth_article_share %}
        <div class="text-center my-4 border p-4 text-muted">
            Vous semblez ne pas avoir partagé d'article
        </div>
    {% endif %}
</section>

templates/user/_menu.html.twig
<div class="mb-4">
    <div class="d-flex flex-column flex-md-row justify-content-between">
        <a href="{{ path('user_dashboard') }}" class="btn btn-secondary mb-4">Tableau de board</a>
        <a href="{{ path('user_info') }}" class="btn btn-secondary mb-4">Informations personnelles</a>
        <a href="{{ path('user_password') }}" class="btn btn-secondary mb-4">Mot de passe</a>
        <a href="{{ path('user_like') }}" class="btn btn-secondary mb-4">Articles aimés</a>
        <a href="{{ path('user_share') }}" class="btn btn-secondary mb-4">Articles partagés</a>
        <a href="{{ path('user_comment') }}" class="btn btn-secondary mb-4">Articles commentés</a>
    </div>
</div>

templates/user/comment.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles commentés{% endblock %}

{% block body %}
    <h1 class="text-center mb-4">Articles commentés</h1>

    {% include "user/_menu.html.twig" %}

    <small>Tous les commentaires que vous avez posté, y compris ce qui n'ont pas été validé par l'admin.</small>
    {% if articles is not empty %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Titre</th>
                    <th scope="col">Catégorie</th>
                    <th scope="col">Contenu</th>
                    <th scope="col">Commentaire</th>
                    <th scope="col">{{ knp_pagination_sortable(articles, 'Date', 'c.createAt') }}</th>
                </tr>
            </thead>
            <tbody>
                {% for comment in articles %}
                    <tr>
                        <th scope="row"><a href="{{ path('article_show', { id: comment.article.id }) }}">{{ comment.article.title }}</th>
                        <th scope="row">{{ comment.article.category }}</th>
                        <th scope="row">{{ comment.article.content|striptags|slice(0,10) ~ '...'|raw }}</th>
                        <th scope="row">{{ comment.content|slice(0,10) ~ '...' }}</th>
                        <th scope="row">{{ comment.createAt|date('d/m/Y') }}</th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="text-center d-flex justify-content-center">
            {{ knp_pagination_render(articles) }}
        </div>
    {% else %}
        <div class="text-center my-4 border p-4 text-muted">
            Aucun article commenté :(
        </div>
    {% endif %}

{% endblock %}

templates/user/dashboard.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tableau de bord{% endblock %}

{% block body %}
    <h1 class="text-center mb-4">Tableau de bord</h1>

    {% include "user/_menu.html.twig" %}

    {% include "user/_latest-like.html.twig" %}

    {% include "user/_latest-share.html.twig" %}

    {% include "user/_latest-comment.html.twig" %}

{% endblock %}

templates/user/info.html.twig
{% extends 'base.html.twig' %}

{% block title %}Informations personnelles{% endblock %}

{% block body %}
    {% for messages in app.flashes('success') %}
        <div class="alert alert-dismissible alert-success">
            <button type="button" class="close" data-dismiss="alert" tabindex="0">&times;</button>
            {{ messages }}
        </div>
    {% endfor %}
    <h1 class="text-center mb-4">Vos informations personnelles</h1>

    {% include "user/_menu.html.twig" %}

    <section>
        <div class="d-flex flex-column">
            {{ form_start(userForm) }}
                {{ form_row(userForm.last_name) }}
                {{ form_row(userForm.first_name) }}
                {{ form_row(userForm.email) }}
                {{ form_row(userForm.phone) }}
                {{ form_row(userForm.captcha) }}
                {{ form_row(userForm.save) }}
            {{ form_end(userForm) }}
        </div>
    </section>

{% endblock %}

templates/user/like.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles aimés{% endblock %}

{% block body %}
    <h1 class="text-center mb-4">Vos articles aimés</h1>

    {% include "user/_menu.html.twig" %}

    {% if articles is not empty %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Image</th>
                    <th scope="col">{{ knp_pagination_sortable(articles, 'Titre', 'a.title') }}</th>
                    <th scope="col">{{ knp_pagination_sortable(articles, 'Auteur', 'a.author') }}</th>
                    <th scope="col">Catégorie</th>
                    <th scope="col">Contenu</th>
                    <th scope="col">{{ knp_pagination_sortable(articles, 'Date', 'a.createAt') }}</th>
                </tr>
            </thead>
            <tbody>
                {% for likes in articles %}
                    <tr>
                        <th scope="row">img</th>
                        <th scope="row"><a href="{{ path('article_show', { id: likes.article.id }) }}">{{ likes.article.title }}</th>
                        <th scope="row">{{ likes.user.firstName }} {{ likes.user.lastName }}</th>
                        <th scope="row">{{ likes.article.category }}</th>
                        <th scope="row">{{ likes.article.content|striptags|slice(0,10) ~ '...'|raw }}</th>
                        <th scope="row">{{ likes.article.publishAt|date('d/m/Y') }}</th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="text-center d-flex justify-content-center">
            {{ knp_pagination_render(articles) }}
        </div>
    {% else %}
        <div class="text-center my-4 border p-4 text-muted">
            Aucun article aimé :(
        </div>
    {% endif %}

{% endblock %}

templates/user/password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Changer son mot de passe{% endblock %}

{% block body %}
    {% for messages in app.flashes('success') %}
        <div class="alert alert-dismissible alert-success">
            <button type="button" class="close" data-dismiss="alert" tabindex="0">&times;</button>
            {{ messages }}
        </div>
    {% endfor %}
    {% for messages in app.flashes('error') %}
        <div class="alert alert-dismissible alert-danger">
            <button type="button" class="close" data-dismiss="alert" tabindex="0">&times;</button>
            {{ messages }}
        </div>
    {% endfor %}
    <h1 class="text-center mb-4">Changer son mot de passe</h1>

    {% include "user/_menu.html.twig" %}

    <section>
        <div class="d-flex flex-column">
            {{ form_start(passForm) }}
                {{ form_row(passForm.oldPassword) }}
                {{ form_row(passForm.newPassword.first) }}
                {{ form_row(passForm.newPassword.second) }}
                {{ form_row(passForm.captcha) }}
                {{ form_row(passForm.save) }}
            {{ form_end(passForm) }}
        </div>
    </section>

{% endblock %}

templates/user/share.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles partagés{% endblock %}

{% block body %}
    <h1 class="text-center mb-4">Vos articles partagés</h1>

    {% include "user/_menu.html.twig" %}

    {% if articles is not empty %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Image</th>
                    <th scope="col">{{ knp_pagination_sortable(articles, 'Titre', 'a.title') }}</th>
                    <th scope="col">{{ knp_pagination_sortable(articles, 'Auteur', 'a.author') }}</th>
                    <th scope="col">Catégorie</th>
                    <th scope="col">Contenu</th>
                    <th scope="col">{{ knp_pagination_sortable(articles, 'Date', 'a.publishAt') }}</th>
                </tr>
            </thead>
            <tbody>
                {% for share in articles %}
                    <tr>
                        <th scope="row">img</th>
                        <th scope="row"><a href="{{ path('article_show', { id: share.article.id }) }}">{{ share.article.title }}</th>
                        <th scope="row">{{ share.user.firstName }} {{ share.user.lastName }}</th>
                        <th scope="row">{{ share.article.category }}</th>
                        <th scope="row">{{ share.article.content|striptags|slice(0,10) ~ '...'|raw }}</th>
                        <th scope="row">{{ share.article.publishAt|date('d/m/Y') }}</th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="text-center d-flex justify-content-center">
            {{ knp_pagination_render(articles) }}
        </div>
    {% else %}
        <div class="text-center my-4 border p-4 text-muted">
            Aucun article partagé :(
        </div>
    {% endif %}

{% endblock %}